# Generated by Django 6.0.3 on 2026-03-13 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_degreeprogram_college'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='college',
        ),
        migrations.AddField(
            model_name='discipline',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='system.degreeprogram'),
        ),
    ]
