# Generated by Django 6.0.4 on 2026-05-07 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='discipline',
            name='year_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.degreeprogram'),
        ),
    ]
