# Generated by Django 6.0.4 on 2026-05-07 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_discipline_semester_discipline_year_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='units',
            field=models.IntegerField(default=3),
        ),
        migrations.CreateModel(
            name='SemesterLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_level', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('max_units', models.IntegerField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.degreeprogram')),
            ],
            options={
                'unique_together': {('program', 'year_level', 'semester')},
            },
        ),
    ]
