# Generated by Django 6.0.4 on 2026-05-07 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_studentprofile_enrolled_disciplines'),
        ('system', '0003_discipline_units_semesterload'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='unlocks', to='system.discipline'),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prelim', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('midterm', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('finals', models.DecimalField(decimal_places=2, max_digits=3)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.discipline')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.studentprofile')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.teacherprofile')),
            ],
            options={
                'unique_together': {('student', 'discipline')},
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ENROLLED', 'Enrolled'), ('DROPPED', 'Dropped'), ('WITHDRAW', 'Withdraw'), ('COMPLETED', 'Completed')], default='ENROLLED', max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='system.discipline')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='profiles.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'discipline')},
            },
        ),
    ]
