# Generated by Django 6.0.4 on 2026-05-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_discipline_prerequisites_grade_studentenrollment'),
    ]

    operations = [
    migrations.AddField(
        model_name='discipline',
        name='code',
        field=models.CharField(default='', max_length=20),  
    ),
    migrations.AlterUniqueTogether(
        name='discipline',
        unique_together={('program', 'code')},
    ),
]
