# Generated by Django 6.0.4 on 2026-05-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_discipline_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='discipline',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='code',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
