# Generated by Django 6.0.4 on 2026-05-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_alter_discipline_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='code',
            field=models.CharField(default='', max_length=10),
        ),
    ]
