# Generated by Django 6.0.4 on 2026-05-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_alter_discipline_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrollment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('ENROLLED', 'Enrolled'), ('DROPPED', 'Dropped'), ('WITHDRAW', 'Withdraw'), ('COMPLETED', 'Completed')], default='ENROLLED', max_length=20),
        ),
    ]
