# Generated by Django 6.0.4 on 2026-05-07 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_studentprofile_enrolled_disciplines'),
        ('system', '0008_alter_studentenrollment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ENROLLED', 'Enrolled'), ('DROPPED', 'Dropped'), ('WITHDRAW', 'Withdraw'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='discipline',
            unique_together={('program', 'code')},
        ),
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(max_length=20)),
                ('semester', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'unique_together': {('school_year', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='SubjectOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_code', models.CharField(editable=False, max_length=5, unique=True)),
                ('schedule', models.CharField(max_length=100)),
                ('room', models.CharField(blank=True, max_length=50)),
                ('max_slots', models.IntegerField(default=40)),
                ('current_slots', models.IntegerField(default=0)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='system.discipline')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offerings', to='profiles.teacherprofile')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='system.academicterm')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='studentenrollment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='offering',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='system.subjectoffering'),
        ),
        migrations.AlterUniqueTogether(
            name='studentenrollment',
            unique_together={('student', 'offering')},
        ),
        migrations.RemoveField(
            model_name='studentenrollment',
            name='discipline',
        ),
    ]
