# Generated by Django 6.0.4 on 2026-05-07 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_studentprofile_enrolled_disciplines'),
        ('system', '0009_alter_discipline_code_alter_studentenrollment_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentenrollment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='discipline',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_requests', to='system.discipline'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='term',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='system.academicterm'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='offering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='system.subjectoffering'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('ENROLLED', 'Enrolled'), ('DROPPED', 'Dropped'), ('WITHDRAWN', 'Withdrawn'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='studentenrollment',
            unique_together={('student', 'discipline', 'term')},
        ),
    ]
