# Generated by Django 6.0.3 on 2026-05-07 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_studentprofile_enrolled_disciplines'),
        ('system', '0010_alter_studentenrollment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='grade',
            name='offering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.subjectoffering'),
        ),
        migrations.AddField(
            model_name='grade',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.academicterm'),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'discipline', 'term')},
        ),
    ]
