# Generated by Django 6.0.3 on 2026-05-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_alter_grade_unique_together_grade_offering_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='finals',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
