# Generated by Django 6.0.4 on 2026-05-06 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='admin_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='teacher_id',
        ),
    ]
