# Generated by Django 6.0.4 on 2026-05-07 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_user_admin_id_remove_user_student_id_and_more'),
        ('system', '0002_discipline_semester_discipline_year_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='system.degreeprogram'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='year_level',
            field=models.IntegerField(default=1),
        ),
    ]
