# Generated by Django 6.0.4 on 2026-05-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_studentprofile_program_studentprofile_year_level'),
        ('system', '0002_discipline_semester_discipline_year_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='enrolled_disciplines',
            field=models.ManyToManyField(blank=True, to='system.discipline'),
        ),
    ]
