# Generated by Django 6.0.4 on 2026-05-07 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_studentprofile_enrolled_disciplines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='enrolled_disciplines',
        ),
    ]
